Readme
butterdao/whip pull request #30
Opened 2022-06-02 16:37 UTC by lajarre

A lot of stuff going on here, as explained by the commit messages.

While adding the CONTRIBUTING docs, I felt the urge to:

- rename `scheduler` to `backend`
- add linting checks to CI.

@acemasterjb you should `pip install -r dev-requirements.txt` from now on, and install all linters (as mentioned in the CONTRIBUTING file) to your editor.

For now, pylint is disabled in CI because it's raising too many problems, but let's add it to our editors and fix files little-by-little from now on.

2022-06-03 14:35 UTC, vaughnmck commented on README.md
> +frotnend if deploying frontend and backend to different (sub-)domains.
small typo on 'frontend'

2022-06-03 14:37 UTC, vaughnmck requested changes
Small typo on line 57 of the README but otherwise happy to merge.

Can you also update the contributing link on line 3 of the README?

2022-06-06 09:26 UTC, acemasterjb commented
Also, is `scheduler` meant to be renamed to `backend` in a future PR? If so, I agree that it should be renamed to `backend` given its contents.

2022-06-06 09:55 UTC, acemasterjb requested changes

2022-06-06 09:55 UTC, acemasterjb commented on README.md
> +```
Has the `dev-requirements.txt` file been pushed yet?

Took a look in the dirs but only found `requirements.txt`

2022-06-06 09:55 UTC, acemasterjb commented on CONTRIBUTING.md
> +- Python: pylint, black, isort, flake8, mypy.
Maybe we should mention the test suite of choice (pytest) somewhere in here as well?

2022-06-06 09:55 UTC, acemasterjb commented on README.md
> +cd frontend && npm run dev
maybe we should mention that the user should install frontend deps with `npm i` before running npm scripts

2022-06-07 10:56 UTC, lajarre commented
After having addressed all pending comments, I'll take the liberty to merge to move forward as this is non critical. Please add more comments if needed, I'll address them separately.

2022-06-07 10:56 UTC, merged