✨ Uniswap V2 LP Tokens
butterdao/whip pull request #88
Opened 2022-07-25 12:42 UTC by acemasterjb

## Summary
Addresses #85

## Details
This PR will introduce LP token prices and balances for treasuries that contains such tokens.

It does so by adding deployed LP tokens from TokenLists and Covalent's xy=k pair lists to Whip's [whitelist](https://github.com/butterdao/whip/pull/52).

## Further improvements
- [ ] Add sushiswap
- [ ] Add Uni_v3 (probably to be addressed in separate PR)

This PR does not require frontend intervention.

2022-07-28 13:03 UTC, lajarre requested changes

2022-07-28 13:03 UTC, lajarre commented on backend/app/libs/storage_helpers/tokenlists.py
> +import os
Apart from the slight remarks that I made I believe the code looks good! As the `tokenlists` module gets a bit more complex (and in an effort to have a clean structure in the codebase), the code would better sit in a different top-level module `app.tokenlists`, with a hexagonal(-ish) structure, as done for `treasury` for example. You'd have adapters for:

- storage (retrieve_token_whitelist, store_token_whitelist)
- covalent
- tokenlists json URLs.

I suggest doing this refactoring in a separate PR.

2022-07-28 16:12 UTC, vaughnmck commented on backend/app/libs/storage_helpers/tokenlists.py
> +                "error receiving uni_v2 pairs from Covalent API", exc_info=error
```suggestion
                "error receiving pairs from Covalent API", exc_info=error
```

2022-07-28 23:22 UTC, acemasterjb commented on backend/app/libs/storage_helpers/tests/conftest.py
> +class MockProvider:
FakeRedis has been utilised for the remaining storage helpers tests.

2022-07-29 11:37 UTC, lajarre approved these changes

2022-07-29 11:45 UTC, merged